global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'paathshala-server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['paathshala-server:5000', 'host.docker.internal:5000']
